path:
  repo: /home/cosine/mygit/linux #repo path
  output : /home/cosine/linuxresult
#select keywords in commit descirption
keyword: 'CVE-'
#limit the time range of commit
time:
  from: 2010-01-01
  to: 2018-05-29
#the files need to save
savefile:
  diff: True   #diff file
  good_file: True   #the file unpatched
  bad_file: True   #the file patched
  description: True   #description about the commit
  keeptype: True   #Weather you want to keep the type of file patched 
#filter the commit
filter:
  maxdiffsnum: 10
  maxchangeline: 20
#You'd better not change the para
pagesize: 100000
